SimplCommerce-master/src/Modules/SimplCommerce.Module.Core/Models/AddressType.cs
namespace SimplCommerce.Module.Core.Models
{
    public enum AddressType
    {
        Shipping,

        Billing
    }
}

SimplCommerce-master/src/Modules/SimplCommerce.Module.Core/Controllers/UserAddressController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SimplCommerce.Infrastructure.Data;
using SimplCommerce.Module.Core.Extensions;
using SimplCommerce.Module.Core.Models;
using SimplCommerce.Module.Core.ViewModels;

namespace SimplCommerce.Module.Core.Controllers
{
    [Authorize]
    public class UserAddressController : Controller
    {
        private readonly IRepository<UserAddress> _userAddressRepository;
        private readonly IRepository<StateOrProvince> _stateOrProvinceRepository;
        private readonly IRepository<District> _districtRepository;
        private readonly IRepository<User> _userRepository;
        private readonly IWorkContext _workContext;

        public UserAddressController(IRepository<UserAddress> userAddressRepository, IRepository<StateOrProvince> stateOrProvinceRepository,
            IRepository<District> districtRepository, IRepository<User> userRepository, IWorkContext workContext)
        {
            _userAddressRepository = userAddressRepository;
            _stateOrProvinceRepository = stateOrProvinceRepository;
            _districtRepository = districtRepository;
            _userRepository = userRepository;
            _workContext = workContext;
        }

        [Route("user/address")]
        public async Task<IActionResult> List()
        {
            var currentUser = await _workContext.GetCurrentUser();
            var model = _userAddressRepository
                .Query()
                .Where(x => x.AddressType == AddressType.Shipping && x.UserId == currentUser.Id)
                .Select(x => new UserAddressListItem
                {
                    AddressId = x.AddressId,
                    UserAddressId = x.Id,
                    ContactName = x.Address.ContactName,
                    Phone = x.Address.Phone,
                    AddressLine1 = x.Address.AddressLine1,
                    AddressLine2 = x.Address.AddressLine1,
                    DistrictName = x.Address.District.Name,
                    StateOrProvinceName = x.Address.StateOrProvince.Name,
                    CountryName = x.Address.Country.Name
                }).ToList();

            foreach (var item in model)
            {
                item.IsDefaultShippingAddress = item.AddressId == currentUser.DefaultShippingAddressId;
            }

            return View(model);
        }

        [Route("user/address/create")]
        public IActionResult Create()
        {
            var model = new UserAddressFormViewModel();

            PopulateAddressFormData(model);

            return View(model);
        }

        [Route("user/address/create")]
        [HttpPost]
        public async Task<IActionResult> Create(UserAddressFormViewModel model)
        {
            if (ModelState.IsValid)
            {
                var currentUser = await _workContext.GetCurrentUser();

                var address = new Address
                {
                    AddressLine1 = model.AddressLine1,
                    ContactName = model.ContactName,
                    CountryId = 1,
                    StateOrProvinceId = model.StateOrProvinceId,
                    DistrictId = model.DistrictId,
                    Phone = model.Phone
                };

                var userAddress = new UserAddress
                {
                    Address = address,
                    AddressType = AddressType.Shipping,
                    UserId = currentUser.Id
                };

                _userAddressRepository.Add(userAddress);
                _userAddressRepository.SaveChange();
                return RedirectToAction("List");
            }

            PopulateAddressFormData(model);
            return View(model);
        }

        [Route("user/address/edit/{id}")]
        public async Task<IActionResult> Edit(long id)
        {
            var currentUser = await _workContext.GetCurrentUser();

            var userAddress = _userAddressRepository.Query()
                .Include(x => x.Address)
                .FirstOrDefault(x => x.Id == id && x.UserId == currentUser.Id);

            if (userAddress == null)
            {
                return NotFound();
            }

            var model = new UserAddressFormViewModel
            {
                Id = userAddress.Id,
                ContactName = userAddress.Address.ContactName,
                Phone = userAddress.Address.Phone,
                AddressLine1 = userAddress.Address.AddressLine1,
                DistrictId = userAddress.Address.DistrictId,
                StateOrProvinceId = userAddress.Address.StateOrProvinceId
            };

            PopulateAddressFormData(model);

            return View(model);
        }

        [Route("user/address/edit/{id}")]
        [HttpPost]
        public async Task<IActionResult> Edit(long id, UserAddressFormViewModel model)
        {
            if (ModelState.IsValid)
            {
                var currentUser = await _workContext.GetCurrentUser();

                var userAddress = _userAddressRepository.Query()
                    .Include(x => x.Address)
                    .FirstOrDefault(x => x.Id == id && x.UserId == currentUser.Id);

                if (userAddress == null)
                {
                    return NotFound();
                }

                userAddress.Address.AddressLine1 = model.AddressLine1;
                userAddress.Address.ContactName = model.ContactName;
                userAddress.Address.CountryId = 1;
                userAddress.Address.StateOrProvinceId = model.StateOrProvinceId;
                userAddress.Address.DistrictId = model.DistrictId;
                userAddress.Address.Phone = model.Phone;

                _userAddressRepository.SaveChange();
                return RedirectToAction("List");
            }

            PopulateAddressFormData(model);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> SetAsDefault(long id)
        {
            var currentUser = await _workContext.GetCurrentUser();

            var userAddress = _userAddressRepository.Query()
                .Include(x => x.Address)
                .FirstOrDefault(x => x.Id == id && x.UserId == currentUser.Id);

            if (userAddress == null)
            {
                return NotFound();
            }

            currentUser.DefaultShippingAddressId = userAddress.AddressId;
            _userRepository.SaveChange();

            return RedirectToAction("List");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(long id)
        {
            var currentUser = await _workContext.GetCurrentUser();

            var userAddress = _userAddressRepository.Query()
                .Include(x => x.Address)
                .FirstOrDefault(x => x.Id == id && x.UserId == currentUser.Id);

            if (userAddress == null)
            {
                return NotFound();
            }

            _userAddressRepository.Remove(userAddress);
            _userAddressRepository.SaveChange();

            return RedirectToAction("List");
        }

        private void PopulateAddressFormData(UserAddressFormViewModel model)
        {
            model.StateOrProvinces = _stateOrProvinceRepository
                .Query()
                .OrderBy(x => x.Name)
                .Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                }).ToList();

            var selectedStateOrProvince = model.StateOrProvinceId > 0 ? model.StateOrProvinceId : long.Parse(model.StateOrProvinces.First().Value);

            model.Districts = _districtRepository
                .Query()
                .Where(x => x.StateOrProvinceId == selectedStateOrProvince)
                .OrderBy(x => x.Name)
                .Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                }).ToList();
        }
    }
}

SimplCommerce-master/src/Modules/SimplCommerce.Module.Core/Views/UserAddress/Create.cshtml
@model SimplCommerce.Module.Core.ViewModels.UserAddressFormViewModel
@{
    ViewData["Title"] = "Create address";
}

<div class="row">
    <div class="col-md-3">
        @Html.Partial("_AccountMenu")
    </div>
    <div class="col-md-9">
        <h2>@Localizer["Create Address"]</h2>
        <hr />
        <form asp-controller="UserAddress" asp-action="Create" method="POST" class="form-horizontal">
            @Html.Partial("_AddressForm", Model)
        </form>
    </div>
</div>

@section scripts {
@{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
<script>
    $(function () {
         $('#StateOrProvinceId').on('change', function () {
            var selectedStateOrProvinceId = this.value;

            $.getJSON("/Location/GetDistricts/" + selectedStateOrProvinceId, function (data) {
                var $districtSelect = $("#DistrictId");
                $districtSelect.empty();

                $.each(data, function (index, option) {
                    $districtSelect.append($("<option></option>").attr("value", option.value).text(option.text));
                });
            });
        });
    });
</script>
}

SimplCommerce-master/src/Modules/SimplCommerce.Module.Core/Views/UserAddress/Edit.cshtml
@model SimplCommerce.Module.Core.ViewModels.UserAddressFormViewModel
@{
    ViewData["Title"] = "Create address";
}

<div class="row">
    <div class="col-md-3">
        @Html.Partial("_AccountMenu")
    </div>
    <div class="col-md-9">
        <h2>@Localizer["Edit Address"]</h2>
        <hr />
        <form asp-controller="UserAddress" asp-action="Edit" method="POST" class="form-horizontal">
            @Html.Partial("_AddressForm", Model)
        </form>
    </div>
</div>

@section scripts {
@{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
<script>
    $(function () {
         $('#StateOrProvinceId').on('change', function () {
            var selectedStateOrProvinceId = this.value;

            $.getJSON("/Location/GetDistricts/" + selectedStateOrProvinceId, function (data) {
                var $districtSelect = $("#DistrictId");
                $districtSelect.empty();

                $.each(data, function (index, option) {
                    $districtSelect.append($("<option></option>").attr("value", option.value).text(option.text));
                });
            });
        });
    });
</script>
}

SimplCommerce-master/src/Modules/SimplCommerce.Module.Core/Views/UserAddress/List.cshtml
@model IEnumerable<SimplCommerce.Module.Core.ViewModels.UserAddressListItem>
@{
    ViewData["Title"] = "Address book";
}

<div class="row">
    <div class="col-md-3">
        @Html.Partial("_AccountMenu")
    </div>
    <div class="col-md-9">
        <h2>@Localizer["Address Book"]</h2>
        <hr />
        @foreach (var address in Model)
        {
            <div>
                <strong>@address.ContactName </strong><br />
                @address.AddressLine1 <br />
                @address.DistrictName, @address.StateOrProvinceName <br />
                Phone: @address.Phone
            </div>
            <div>
                @if (address.IsDefaultShippingAddress)
                {
                    <span class="label label-primary">@Localizer["Default shipping address"]</span>
                }
                else
                {
                    <form method="post" style="display: inline" asp-controller="UserAddress" asp-action="SetAsDefault" asp-route-id="@address.UserAddressId">
                        <button type="submit" class="btn btn-link" style="padding: 0">@Localizer["Set as default shipping address"]</button>
                    </form>
                    <span> | </span>
                }
                <a href="~/user/address/edit/@address.UserAddressId">@Localizer["Edit"]</a><span> | </span>
                <form method="post" style="display: inline" asp-controller="UserAddress" asp-action="Delete" asp-route-id="@address.UserAddressId">
                    <button type="submit" class="btn btn-link" style="padding: 0">@Localizer["Delete"]</button>
                </form>
            </div>
            <hr />
        }

        <div class="text-right"><a class="btn btn-primary" href="~/user/address/create">@Localizer["Add Address"]</a></div>
    </div>
</div>

SimplCommerce-master/src/Modules/SimplCommerce.Module.Core/Views/UserAddress/_AddressForm.cshtml
@model SimplCommerce.Module.Core.ViewModels.UserAddressFormViewModel

<div class="form-group">
    <label class="col-sm-2 control-label">@Localizer["Contact name"]</label>
    <div class="col-sm-10">
        <input asp-for="ContactName" type="text" class="form-control">
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">@Localizer["Address"]</label>
    <div class="col-sm-10">
        <input asp-for="AddressLine1" type="text" class="form-control">
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">@Localizer["State or Province"]</label>
    <div class="col-sm-10">
        <select asp-for="StateOrProvinceId" asp-items="Model.StateOrProvinces" class="form-control"></select>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">@Localizer["District"]</label>
    <div class="col-sm-10">
        <select asp-for="DistrictId" asp-items="Model.Districts" class="form-control"></select>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">@Localizer["Phone"]</label>
    <div class="col-sm-10">
        <input asp-for="Phone" type="text" class="form-control">
    </div>
</div>
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <button type="submit" class="btn btn-primary">@Localizer["Save"]</button>
        <a href="~/user/address" class="btn btn-default">@Localizer["Cancel"]</a>
    </div>
</div>